### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by duralog** [lukeweber/webrtc-jingle-client#49]
tried with both the lukeweber ndk and the one that comes with homebrew.

when running `gclient sync` I get the following error:

```
________ running '/usr/bin/python trunk/tools/create_supplement_gypi.py trunk/voice-client-core/supplement.gypi' in '/Users/kenny/Projects/freemando'
Traceback (most recent call last):
  File "trunk/tools/create_supplement_gypi.py", line 26, in <module>
    sys.exit(main(sys.argv))
  File "trunk/tools/create_supplement_gypi.py", line 23, in main
    open(argv[1], 'w').write(supplement_gypi % argv[0])
IOError: [Errno 2] No such file or directory: 'trunk/voice-client-core/supplement.gypi'
Error: Command /usr/bin/python trunk/tools/create_supplement_gypi.py trunk/voice-client-core/supplement.gypi returned non-zero exit status 1 in /Users/kenny/Projects/freemando
```

**Comment by duralog** [comment]
all fixed. thanks :)
