### ISSUE TITLE
Maven compilation error

### ISSUE THREAD

**Issue by vkotovv** [lukeweber/webrtc-jingle-client#65]
I've tried to compile the project according to the instructions in the README, but it produces the following output:

```
[ERROR] Error while copying gdbserver: gdbserver binary /home/vadim/Apps/android-ndk-r8d/toolchains/arm-linux-androideabi-4.4.3/prebuilt/gdbserver does not exist, please double check the toolchain and OS used
org.apache.maven.plugin.MojoExecutionException: gdbserver binary /home/vadim/Apps/android-ndk-r8d/toolchains/arm-linux-androideabi-4.4.3/prebuilt/gdbserver does not exist, please double check the toolchain and OS used
    at com.jayway.maven.plugins.android.AndroidNdk.getGdbServer(AndroidNdk.java:186)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.optionallyCopyGdbServer(ApkMojo.java:961)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.processNativeLibraries(ApkMojo.java:947)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.processNativeLibraries(ApkMojo.java:833)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.createApkFile(ApkMojo.java:377)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.execute(ApkMojo.java:332)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.970s
[INFO] Finished at: Tue Feb 05 23:45:53 MYT 2013
[INFO] Final Memory: 15M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.1-SNAPSHOT:apk (default-apk) on project voice-example: Error while copying gdbserver: gdbserver binary /home/vadim/Apps/android-ndk-r8d/toolchains/arm-linux-androideabi-4.4.3/prebuilt/gdbserver does not exist, please double check the toolchain and OS used -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.1-SNAPSHOT:apk (default-apk) on project voice-example: Error while copying gdbserver: gdbserver binary /home/vadim/Apps/android-ndk-r8d/toolchains/arm-linux-androideabi-4.4.3/prebuilt/gdbserver does not exist, please double check the toolchain and OS used
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error while copying gdbserver: gdbserver binary /home/vadim/Apps/android-ndk-r8d/toolchains/arm-linux-androideabi-4.4.3/prebuilt/gdbserver does not exist, please double check the toolchain and OS used
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.optionallyCopyGdbServer(ApkMojo.java:977)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.processNativeLibraries(ApkMojo.java:947)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.processNativeLibraries(ApkMojo.java:833)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.createApkFile(ApkMojo.java:377)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.execute(ApkMojo.java:332)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: org.apache.maven.plugin.MojoExecutionException: gdbserver binary /home/vadim/Apps/android-ndk-r8d/toolchains/arm-linux-androideabi-4.4.3/prebuilt/gdbserver does not exist, please double check the toolchain and OS used
    at com.jayway.maven.plugins.android.AndroidNdk.getGdbServer(AndroidNdk.java:186)
    at com.jayway.maven.plugins.android.phase09package.ApkMojo.optionallyCopyGdbServer(ApkMojo.java:961)
    ... 25 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I have Android NDK and SDK installed, what can be the issue? Thanks in advance.

**Comment by jreyes** [comment]
It's looking for /home/vadim/Apps/android-ndk-r8d/toolchains/arm-linux-androideabi-4.4.3/prebuilt/gdbserver and it can not find it, check your files to see if it exists.

**Comment by lukeweber** [comment]
Ah this is a maven bug I think of them hunting for gen in the wrong place.
Just symlink gdb from where they want it to where it is really in the ndk
and it should work.

**Comment by vkotovv** [comment]
Yeah, thanks, symlink helped. Maybe you should state this fact somewhere in the FAQ, troubleshooting? Just the error and the link to this issue.

**Comment by lukeweber** [comment]
Issue has been fixed upstream in the maven-android-plugin. 

https://github.com/lukeweber/maven-android-plugin/commit/4f18d33c880337b90b6e36f5887274889681dd4d

Updated to newest version of plugin to resolve.

https://github.com/lukeweber/webrtc-jingle-client/commit/bd6f6dc8524d805ca14109feedc66b2c13cf4157
