### ISSUE TITLE
Running build command for iOS

### ISSUE THREAD

**Issue by garayronald** [lukeweber/webrtc-jingle-client#92]
I've been following the steps to get the xcode project for iOS. Wen i run the ./build/gyp_chromium command I get this:

./build/gyp_chromium --depth=.  -DOS=ios -Dinclude_tests=0 -Denable_protobuf=0 -Denable_video=0 webrtcjingle.gyp
Updating projects from gyp files...
Traceback (most recent call last):
  File "./build/gyp_chromium", line 146, in <module>
    sys.exit(gyp.main(args))
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/**init**.py", line 523, in main
    return gyp_main(args)
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/**init**.py", line 499, in gyp_main
    options.circular_check)
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/**init**.py", line 129, in Load
    params['parallel'])
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/input.py", line 2556, in Load
    variables, includes, depth, check, True)
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/input.py", line 1213, in ProcessVariablesAndConditionsInDict
    build_file, key)
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/input.py", line 1194, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/input.py", line 1073, in ProcessConditionsInDict
    MergeDicts(the_dict, merge_dict, build_file, build_file)
  File "/Users/Ronald/Documents/Vensi/WebRTC/webrtcjingleproject/trunk/tools/gyp/pylib/gyp/input.py", line 1942, in MergeDicts
    ' for key ' + k
TypeError: Attempt to merge dict value of type list into incompatible type str for key ARCHS while trying to load webrtcjingle.gyp

Any reason why?

**Comment by lukeweber** [comment]
./build/gyp_chromium --depth=. -DOS=ios -Dinclude_tests=0 -Denable_protobuf=0 -Denable_video=0 webrtcjingle.gyp
Updating projects from gyp files...

![screen shot 2013-05-16 at 11 32 57 pm](https://f.cloud.github.com/assets/195363/515244/5450a08e-be70-11e2-94d2-9e1ae3acd401.png)

It seems to work fine for me. 

Maybe something is wrong in your environment and it's being pulled into gyp and causing it to fail. GYP does read a bit of environment state to try to decide how to build and seems the var ARCHS is wrong.
