### ISSUE TITLE
third_party/gtest/include/gtest/gtest.h:284:25: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by bic-user** [lukeweber/webrtc-jingle-client#99]
[DEBUG] Compile++ x86    : jingle_media_unittest <= rtpdataengine_unittest.cc
[INFO] In file included from jni/../../../third_party/libjingle/talk/base/gunit.h:34:0,
[INFO]                  from jni/../../../third_party/libjingle/talk/media/base/codec_unittest.cc:28:
[INFO] jni/../../../third_party/gtest/include/gtest/gtest.h:284:25: internal compiler error: Segmentation fault
[INFO] Please submit a full bug report,
[INFO] with preprocessed source if appropriate.
[INFO] See http://source.android.com/source/report-bugs.html for instructions.
[INFO] make: **\* [/home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native/obj/default_debug/local/x86/objs-debug/jingle_media_unittest/talk/media/base/codec_unittest.o] Error 1
[INFO] make: **\* Waiting for unfinished jobs....
[DEBUG] make: Leaving directory `/home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native'
[DEBUG] ANDROID-040-000: Executed command: Commandline = /bin/sh -c cd /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native && /home/vklimkov/Project/android-ndk-r8e/ndk-build -C /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native NDK_APPLICATION_MK=jni/default_debug.mk -j 8 NDK_APP_OUT=/home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native/obj/default_debug all, Result = 2
[ERROR] Error while executing: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native && /home/vklimkov/Project/android-ndk-r8e/ndk-build -C /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native NDK_APPLICATION_MK=jni/default_debug.mk -j 8 NDK_APP_OUT=/home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native/obj/default_debug all, Result = 2
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Tuenti Voice Client Parent ........................ SUCCESS [0.106s]
[INFO] Tuenti Voice Client Core .......................... SUCCESS [0.972s]
[INFO] Tuenti Voice Client Native Library ................ FAILURE [7:46.210s]
[INFO] Tuenti Voice Client AIDL .......................... SKIPPED
[INFO] Tuenti Voice Client Example ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7:48.051s
[INFO] Finished at: Sun Jun 23 22:58:54 FET 2013
[INFO] Final Memory: 19M/177M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.3:ndk-build (default-ndk-build) on project voice-native: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native && /home/vklimkov/Project/android-ndk-r8e/ndk-build -C /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native NDK_APPLICATION_MK=jni/default_debug.mk -j 8 NDK_APP_OUT=/home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native/obj/default_debug all, Result = 2 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.5.3:ndk-build (default-ndk-build) on project voice-native: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native && /home/vklimkov/Project/android-ndk-r8e/ndk-build -C /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native NDK_APPLICATION_MK=jni/default_debug.mk -j 8 NDK_APP_OUT=/home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native/obj/default_debug all, Result = 2
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native && /home/vklimkov/Project/android-ndk-r8e/ndk-build -C /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native NDK_APPLICATION_MK=jni/default_debug.mk -j 8 NDK_APP_OUT=/home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native/obj/default_debug all, Result = 2
    at com.jayway.maven.plugins.android.phase05compile.NdkBuildMojo.execute(NdkBuildMojo.java:462)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: com.jayway.maven.plugins.android.ExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native && /home/vklimkov/Project/android-ndk-r8e/ndk-build -C /home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native NDK_APPLICATION_MK=jni/default_debug.mk -j 8 NDK_APP_OUT=/home/vklimkov/Project/vb/lukeweber/webrtcjingleproject/trunk/android/voice-client-native/obj/default_debug all, Result = 2
    at com.jayway.maven.plugins.android.CommandExecutor$Factory$1.executeCommand(CommandExecutor.java:339)
    at com.jayway.maven.plugins.android.phase05compile.NdkBuildMojo.execute(NdkBuildMojo.java:448)
    ... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :voice-native

building head version with default_debug fails with this error. Not sure if it's issue, but I exactly followed instruction, so should be ok on my side. Thanks in advance.

**Comment by bic-user** [comment]
For default-release.mk builds ok

**Comment by bic-user** [comment]
One more question (sorry for posting in the same thread). I'm unable to login. I read that RFC and relay host are not mandatory, so I didn't provide them. I enter email and login, press button and nothing happens. Here is android log: http://pastebin.com/zUM9w9xL, but it's not really informative..

**Comment by lukeweber** [comment]
With what's there it should allow you to log into a Google account. If
you're trying to log into a different xmpp server make sure isgtalk is set
to false on login.

I haven't seen the error you had on x86. Maybe bad build cache.

**Comment by bic-user** [comment]
My bad. login seems to be refused due to unstable inet connection. Thanks you very much for help!

**Comment by alonewolf** [comment]
bic-user ： what doses  this answer  mean " For default-release.mk builds ok"
 I happend the same building wrong  like you,  can you tell me the detail  of you solving.
